name: Ruff Check Python Project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Ruff-Check-Python-Project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install the code linting and formatting tool Ruff
      run: pipx install ruff
    - name: Lint code with Ruff
      run: ruff check --output-format=github --target-version=py39
    - name: Check code formatting with Ruff
      run: ruff format --diff --target-version=py39
      continue-on-error: true
